[build]
  command = "make build"
  functions = "functions"
  publish = "site"

[build.environment]
  GO_IMPORT_PATH = "github.com/fazarth/sipil_api"
  GO111MODULE = "on"

[[redirects]]
  from = "/*"
  to = "/server.go"
  status = 200